"""
This module contains the handle_events function which is used to process the events in a pygame application.

Functions:
    handle_events(): Processes the events generated by the Pygame library and performs the necessary actions based on the event type.

The handle_events function returns a boolean value indicating whether the game should continue running or not. It loops through all the events in the Pygame event queue, and if it finds a QUIT event, it returns False, indicating that the game should stop running. If no QUIT event is found, it returns True, indicating that the game should continue running.
"""
import pygame

def handle_events():
    """
    Handle events in the game.

    This function processes the events generated by the Pygame library and
    performs the necessary actions based on the event type. It returns a boolean
    value indicating whether the game should continue running or not.

    Returns:
        bool: True if the game should continue running, False otherwise.
    """
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            return False
    return True